// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBzfjkR-xtRvOaZWIYeh6ZESLGzAmyXrw',
    appId: '1:649003480596:web:dbf2f6882dfde49c651901',
    messagingSenderId: '649003480596',
    projectId: 'atelier4-i-elfarouki-iir5g2',
    authDomain: 'atelier4-i-elfarouki-iir5g2.firebaseapp.com',
    storageBucket: 'atelier4-i-elfarouki-iir5g2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8m1OaHGDFaahiJNkWWBeX6TpqhqoiPn4',
    appId: '1:649003480596:android:bfb5d47bbbad074d651901',
    messagingSenderId: '649003480596',
    projectId: 'atelier4-i-elfarouki-iir5g2',
    storageBucket: 'atelier4-i-elfarouki-iir5g2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgoHw_yur3XgY7r1JQ_4RMXLT-_Fq0AdI',
    appId: '1:649003480596:ios:7f1b72ba646c9871651901',
    messagingSenderId: '649003480596',
    projectId: 'atelier4-i-elfarouki-iir5g2',
    storageBucket: 'atelier4-i-elfarouki-iir5g2.appspot.com',
    iosBundleId: 'com.example.produits',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCgoHw_yur3XgY7r1JQ_4RMXLT-_Fq0AdI',
    appId: '1:649003480596:ios:ef617ea87724094d651901',
    messagingSenderId: '649003480596',
    projectId: 'atelier4-i-elfarouki-iir5g2',
    storageBucket: 'atelier4-i-elfarouki-iir5g2.appspot.com',
    iosBundleId: 'com.example.produits.RunnerTests',
  );
}
